// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXcws7L1CJjpUJodaIu02NDw4phQH7EQc',
    appId: '1:619912409585:web:5b68dcf15ac4bf919e5450',
    messagingSenderId: '619912409585',
    projectId: 'pulo-9750d',
    authDomain: 'pulo-9750d.firebaseapp.com',
    storageBucket: 'pulo-9750d.appspot.com',
    measurementId: 'G-2FPYGQF59B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl5WIUPtrnSmQGRosTLnIbti4HqJ47FwY',
    appId: '1:619912409585:android:ebf85cf7ea075c6b9e5450',
    messagingSenderId: '619912409585',
    projectId: 'pulo-9750d',
    storageBucket: 'pulo-9750d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQl716peOX0-Fl0lXOvP0Zi2yhwOmGSM0',
    appId: '1:619912409585:ios:d16cd008a6109df29e5450',
    messagingSenderId: '619912409585',
    projectId: 'pulo-9750d',
    storageBucket: 'pulo-9750d.appspot.com',
    iosBundleId: 'com.example.usersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQl716peOX0-Fl0lXOvP0Zi2yhwOmGSM0',
    appId: '1:619912409585:ios:bc99489cbdd483739e5450',
    messagingSenderId: '619912409585',
    projectId: 'pulo-9750d',
    storageBucket: 'pulo-9750d.appspot.com',
    iosBundleId: 'com.example.usersApp.RunnerTests',
  );
}
